### ISSUE TITLE
Per-project dockerized Python virtual environment

### ISSUE THREAD

**Issue by sfavazza** [emacs-lsp/lsp-docker#76]
Hello there, as mentioned in the object, I would like to create a per-project docker, such that each of them contain a project-specific Python virtual environment where installing (among others) the pylsp package.

The idea would be to have some dir-locals explicitly selecting the dockerized version of the `pylsp` server instead of the system-wide installed one.

I read multiple times the documentation of this repo and the one from the lsp-mode, though I cannot yet achieve my goal.

In a first attempt I tried with the following `.lsp-docker.yml` file:
```yml
lsp:
  server:
    type: docker
    subtype: image
    name: "mylspserver" # manually created image with this name
    server: "pylsp" 
    launch_command: "pylsp"
  mappings:
    - source: "."
      destination: "/code"
```

Hence invoking `lsp-docker-register` would install this server, but I guess this simply replaces the global lang-server for Python, as switching to another project still shows the same server connection pointing to `mylspserver`.

I then tried to create a unique ID client in lsp with:
```elisp
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "pylsp")
                  :activation-fn (lsp-activate-on "python")
                  :server-id 'my-fancy-pylsp))
```
Changing the `server` key-word in `.lsp-docker.yml` to `my-fancy-pylsp` allow me to keep `pylsp` server intact and just add the `my-fancy-pylsp`. Though I don't know how to prevent other projects from pointing at `my-fancy-pylsp`.

This seconds approach is not nice as it implies to always create a new server (for each new project) with a unique name that is not local to the project.

Am I missing something here? Is it possible at all to achieve my goal?

If a neat solution can be found, I am willing to add this use-case to the `lsp-docker` documentation with a MR.
